CREATE TABLE properties_list (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    price FLOAT UNSIGNED DEFAULT 0,
    number_of_rooms TINYINT(3) UNSIGNED DEFAULT 0,
    number_of_bathrooms FLOAT UNSIGNED DEFAULT 0,
    area_sqft FLOAT UNSIGNED DEFAULT 0,
    property_state TINYINT(3) UNSIGNED NOT NULL,
    address_street VARCHAR(50) DEFAULT '',
    address_apartment VARCHAR(10) DEFAULT '',
    address_city VARCHAR(50) DEFAULT '',
    address_state VARCHAR(50) DEFAULT '',
    address_zip MEDIUMINT(8) UNSIGNED DEFAULT 0,
    description TEXT NOT NULL,
    heating_type VARCHAR(50) DEFAULT NULL,
    cooling_type VARCHAR(50) DEFAULT NULL,
    appliances TEXT DEFAULT NULL,
    flooring_type VARCHAR(50) DEFAULT NULL,
    basement TINYINT(1) DEFAULT 0,
    fireplace TINYINT(1) DEFAULT 0,
    levels INT(11) NOT NULL,
    parcel_number VARCHAR(100) NOT NULL,
    special_conditions TEXT DEFAULT NULL,
    size_lot DECIMAL(10,2) DEFAULT NULL,
    price_per_squarefeet DECIMAL(10,2) DEFAULT NULL,
    built_in_year YEAR(4) DEFAULT NULL,
    home_type VARCHAR(50) NOT NULL,
    materials TEXT DEFAULT NULL,
    sewer_type VARCHAR(50) DEFAULT NULL,
    water_type VARCHAR(50) DEFAULT NULL,
    hoa_cost DECIMAL(10,2) DEFAULT NULL,
    enrollment_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
